In [1]:
import sympy
import numpy as np
from matplotlib import pyplot as plt
from pysr import PySRRegressor
from sklearn.model_selection import train_test_split

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython


In [2]:
import pandas as pd

# Tegmark repository

In [3]:
# Reads the equations
df = pd.read_csv('FeynmanEquations.csv')

## Gaussian distribution

In [4]:
df['Formula'][1]

'exp(-(theta/sigma)**2/2)/(sqrt(2*pi)*sigma)'

In [5]:
sympy.simplify(df['Formula'][1])

sqrt(2)*exp(-theta**2/(2*sigma**2))/(2*sqrt(pi)*sigma)

In [6]:
data = []
with open('./data/I.6.2', 'r') as file:
    for line in file:
        float_line = [float(x) for x in line.strip().split()]
        data.append(float_line)

In [7]:
data[:5]

[[2.564830477319424, 1.0663712017158176, 0.1426641647178555],
 [2.8932169466669677, 2.8713313517397934, 0.08426643057964915],
 [2.3150505694914836, 1.6346393044277656, 0.13430348728451916],
 [1.4298257485557877, 2.852188446260336, 0.038156252873846254],
 [2.293784737145745, 2.82801732058014, 0.08133585378750949]]

In [8]:
data = np.array(data)
data[:, 0]

array([2.56483048, 2.89321695, 2.31505057, ..., 2.97097419, 1.98654694,
       1.68419834])

In [9]:
# Dataset
X = data[:800, :2]
theta = X[:,0]
sigma = X[:,1]
#theta, sigma
y = data[:800, 2]
#y

In [10]:
#X

In [11]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

In [12]:
# Learn equations
model = PySRRegressor(
    niterations=100,
    binary_operators=["*", "/"],
    unary_operators=["exp", "sq(x) = x^2"],
    extra_sympy_mappings={"sq": lambda x: x**2},
    **default_pysr_params,
)

model.fit(X, y)

/home/paolo/.conda/envs/coderefinery/lib/python3.11/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
Compiling Julia backend...
[ Info: Started!



Expressions evaluated per second: 1.980e+05
Progress: 1122 / 3000 total iterations (37.400%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           1.759e-03  0.000e+00  y = 0.11316
3           4.381e-04  6.951e-01  y = 0.20787 / x₁
6           4.101e-04  2.202e-02  y = 0.34355 / exp(x₁ * 0.58058)
10          9.072e-05  3.771e-01  y = exp(x₁ * (-1.0758 / x₀)) / (x₀ / 0.66369)
14          6.145e-13  4.703e+00  y = exp((((x₁ * x₁) / x₀) / x₀) * -0.5) / (x₀ / 0.39895)
16          7.242e-14  1.069e+00  y = exp(((x₁ * x₁) * ((0.99996 / x₀) * -0.50002)) / x₀) / ...
                                      (x₀ / 0.39894)
25          7.219e-14  3.451e-04  y = exp(x₁ * (((x₁ / x₀) * -0.50002) / (x₀ * exp(0.41776 /...
                                       ((x₀ / 0.87024) / (x₁ * 4.8373e-05)))))) / (

[ Info: Final population:
[ Info: Results saved to:


PySRRegressor.equations_ = [
	   pick      score                                           equation  \
	0         0.000000                                         0.11315549   
	1         0.695142                                    0.20787439 / x1   
	2         0.022023                  0.34347293 / exp(x1 * 0.58046097)   
	3         0.377146     exp(x1 * (-1.0758005 / x0)) / (x0 / 0.6636941)   
	4        27.785738  exp(-0.49999997 / sq(x0 / x1)) / (x0 / 0.39894...   
	5         0.034036  exp(x1 * ((x1 / sq(x0)) * -0.49999997)) / (x0 ...   
	6         0.092836  exp(-0.5 * sq(x1 / x0)) / (((x0 / x0) / 0.3989...   
	7         0.008551  exp((x1 * (x1 / sq(x0))) * -0.5) / (x0 * ((x0 ...   
	8  >>>>   0.159344  exp(((x1 / x0) * (x1 * -0.5)) / x0) / (x0 * ((...   
	
	           loss  complexity  
	0  1.759348e-03           1  
	1  4.380856e-04           3  
	2  4.100767e-04           6  
	3  9.071831e-05          10  
	4  7.771452e-17          11  
	5  7.260034e-17          13  
	6  6.029791e-17          15  
	7  5.927550e-17          17  
	8  5.054442e-17          18  
]

  - outputs/20250926_122258_MQNCE0/hall_of_fame.csv


In [13]:
model.sympy()

exp(x1*x1*(-0.5)/(x0*x0))/((x0*x0/(0.39894226*x0)))

In [14]:
1/np.sqrt(2*np.pi)

0.3989422804014327

## Train test split

In [15]:
# Dataset
X = data[:1000, :2]
y = data[:1000, 2]
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=0)
theta_train = X_train[:,0]
sigma_train = X_train[:,1]
theta_test = X_test[:,0]
sigma_test = X_test[:,1]

In [16]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

In [17]:
# Learn equations
model = PySRRegressor(
    niterations=100,
    binary_operators=["*", "/"],
    unary_operators=["exp", "sq(x) = x^2"],
    extra_sympy_mappings={"sq": lambda x: x**2},
    **default_pysr_params,
)

model.fit(X_train, y_train)

/home/paolo/.conda/envs/coderefinery/lib/python3.11/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!



Expressions evaluated per second: 1.710e+05
Progress: 1055 / 3000 total iterations (35.167%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           1.804e-03  0.000e+00  y = 0.11185
3           4.678e-04  6.748e-01  y = 0.20608 / x₁
6           4.279e-04  2.974e-02  y = 0.34152 / exp(x₁ / 1.7201)
8           1.074e-04  6.913e-01  y = 0.6173 / (x₀ * exp(x₁ / x₀))
10          9.562e-05  5.797e-02  y = 0.66319 / (exp((x₁ / x₀) * 1.0791) * x₀)
11          1.401e-16  2.725e+01  y = 0.39894 / (exp(sq(x₁ * (0.70711 / x₀))) * x₀)
13          1.370e-16  1.103e-02  y = 0.39894 / (exp(sq((x₁ / 1.4142) * (1 / x₀))) * x₀)
23          1.207e-16  1.270e-02  y = 0.39894 / (exp(sq(x₁ * ((exp(-3.6962e-05 / ((exp(x₀ / ...
                                      x₁) / -0.019642) * 0.78329)) / 1.4142) / x₀))) 

[ Info: Final population:
[ Info: Results saved to:


PySRRegressor.equations_ = [
	   pick      score                                           equation  \
	0         0.000000                                        0.111851566   
	1         0.674830                                    0.20608288 / x1   
	2         0.029744                   0.34152472 / exp(x1 / 1.7201153)   
	3         0.004350              0.7249251 / exp(exp(x1 * 0.31798345))   
	4         1.378183                   0.61730486 / (x0 * exp(x1 / x0))   
	5         0.058131      0.6619692 / (exp(x1 / (x0 / 1.0760016)) * x0)   
	6        27.564854  0.3989423 / (x0 * exp(sq((x1 / x0) * 0.7071067...   
	7         0.058203  0.3989423 / (exp(sq(((x1 / x0) * 0.7071061) / ...   
	8         0.037842  0.3989423 / (x0 * exp(sq((x1 / x0) * 0.7071061...   
	9  >>>>   0.143887  0.3989423 / (exp(((x1 / x0) * x1) * ((0.499999...   
	
	           loss  complexity  
	0  1.803990e-03           1  
	1  4.678256e-04           3  
	2  4.278888e-04           6  
	3  4.260315e-04           7  
	4  1.073753e-04           8  
	5  9.559006e-05          10  
	6  1.021290e-16          11  
	7  9.090645e-17          13  
	8  8.753068e-17          14  
	9  6.564194e-17          16  
]

  - outputs/20250926_122318_cfaV2U/hall_of_fame.csv


In [18]:
model.sympy()

0.3989423/((x0*exp(x1*x1*0.49999955/(x0*x0*0.99999905))))

In [19]:
ypredict = model.predict(X_test)
# Computes the MSE <(ypredict - y)^2>
print("Default selection MSE:", np.power(ypredict - y_test, 2).mean())

Default selection MSE: 1.393858600583851e-17


## Gravitational formula in 3D

In [6]:
sympy.simplify(df['Formula'][4])

G*m1*m2/((x1 - x2)**2 + (y1 - y2)**2 + (z1 - z2)**2)

In [7]:
sympy.expand(sympy.simplify(df['Formula'][4]))

G*m1*m2/(x1**2 - 2*x1*x2 + x2**2 + y1**2 - 2*y1*y2 + y2**2 + z1**2 - 2*z1*z2 + z2**2)

In [8]:
data = []
entry = df['Filename'][4]
with open(f'./data/{entry}', 'r') as file:
    for line in file:
        float_line = [float(x) for x in line.strip().split()]
        data.append(float_line)

In [9]:
data[:3]

[[1.8713055326412502,
  1.0034480251479807,
  1.4573398867123015,
  3.927323289786794,
  1.0338899958093903,
  3.2516726878475066,
  1.91158690483094,
  3.531639561705637,
  1.4131164955760318,
  0.18671842217267526],
 [1.808359710690784,
  1.888191130541064,
  1.1700083522943014,
  3.9460692884442943,
  1.1586814965781298,
  3.321795862499887,
  1.8989500490089544,
  3.9122131670461195,
  1.0609920020361066,
  0.22289346141204303],
 [1.3140296599405707,
  1.1341163486796548,
  1.584233779002786,
  3.9541727371365933,
  1.9032366118772042,
  3.2446283989093927,
  1.5810304725687252,
  3.0123984645744963,
  1.6277773919237948,
  0.26553874197089344]]

In [10]:
arr = np.array(data[:800])
arr[:3], arr.shape

(array([[1.87130553, 1.00344803, 1.45733989, 3.92732329, 1.03389   ,
         3.25167269, 1.9115869 , 3.53163956, 1.4131165 , 0.18671842],
        [1.80835971, 1.88819113, 1.17000835, 3.94606929, 1.1586815 ,
         3.32179586, 1.89895005, 3.91221317, 1.060992  , 0.22289346],
        [1.31402966, 1.13411635, 1.58423378, 3.95417274, 1.90323661,
         3.2446284 , 1.58103047, 3.01239846, 1.62777739, 0.26553874]]),
 (800, 10))

In [11]:
# Dataset
X = arr[:, :9]
m1 = X[:,0]
m2 = X[:,1]
G = X[:,2]
x1 = X[:,3]
x2 = X[:,4]
y1 = X[:,5]
y2 = X[:,6]
z1 = X[:,7]
z2 = X[:,8]
#theta, sigma
y = arr[:, 9]

In [60]:
r = np.sqrt((x1-x2)**2 + (y1-y2)**2  + (z1-z2)**2)
red_X = np.vstack((m1, m2, G, r)).T

In [61]:
red_X

array([[1.87130553, 1.00344803, 1.45733989, 3.82830591],
       [1.80835971, 1.88819113, 1.17000835, 4.23361347],
       [1.31402966, 1.13411635, 1.58423378, 2.98179016],
       ...,
       [1.2492723 , 1.62560002, 1.43596808, 3.20761271],
       [1.66643626, 1.7680461 , 1.09803292, 3.17852966],
       [1.3406618 , 1.93043857, 1.75476337, 3.35661377]])

In [46]:
red_X.shape

(800, 4)

In [47]:
X

array([[1.87130553, 1.00344803, 1.45733989, ..., 1.9115869 , 3.53163956,
        1.4131165 ],
       [1.80835971, 1.88819113, 1.17000835, ..., 1.89895005, 3.91221317,
        1.060992  ],
       [1.31402966, 1.13411635, 1.58423378, ..., 1.58103047, 3.01239846,
        1.62777739],
       ...,
       [1.2492723 , 1.62560002, 1.43596808, ..., 1.42645594, 3.14785256,
        1.41486756],
       [1.66643626, 1.7680461 , 1.09803292, ..., 1.97501942, 3.56992166,
        1.66019458],
       [1.3406618 , 1.93043857, 1.75476337, ..., 1.23830632, 3.22593331,
        1.90110934]])

In [29]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

In [62]:
# Learn equations
model = PySRRegressor(
    niterations=600,
    binary_operators=["+", "-", "*", "/"],
    # unary_operators=["inv(x) = 1/x"],
    # extra_sympy_mappings={"inv": lambda x: 1/x},
    #maxsize = 20
)

#model.fit(X, y, variable_names=["m1", "m2", "G", "x1", "x2", "y1", "y2", "z1", "z2"])
model.fit(red_X, y, variable_names=["m1", "m2", "G", "r"])

/home/paolo/.conda/envs/coderefinery/lib/python3.11/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!



Expressions evaluated per second: 3.060e+05
Progress: 1802 / 18600 total iterations (9.688%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           1.410e-02  0.000e+00  y = 0.27732
3           1.038e-02  1.530e-01  y = 0.97942 / r
5           6.307e-03  2.492e-01  y = 0.53363 / (r - m1)
7           3.478e-03  2.977e-01  y = (G * -0.3487) / (m2 - r)
9           5.465e-16  1.474e+01  y = ((m1 * m2) / r) * (G / r)
11          5.438e-16  2.482e-03  y = (G / (r + 0)) * ((m1 * m2) / r)
15          5.420e-16  8.308e-04  y = ((G / ((r - -0.22638) + -0.22638)) * ((m1 * m2) / r)) ...
                                      + 0
17          5.376e-16  4.049e-03  y = ((G / r) + ((1.3287e-08 / r) * (m1 / 0.60728))) * ((m2...
                                       * m1) / r)
19          5.360e-16  1.486

[ Info: Final population:
[ Info: Results saved to:


PySRRegressor.equations_ = [
	   pick      score                                           equation  \
	0         0.000000                                          0.2773229   
	1         0.153021                                      0.9794189 / r   
	2         0.249359                             -0.53145367 / (m1 - r)   
	3         0.328661                        m2 * (-0.3484667 / (G - r))   
	4  >>>>  14.709707                          ((m1 * m2) / r) * (G / r)   
	5         0.002482                  (G / (r + 0.0)) * ((m1 * m2) / r)   
	6         0.010835   ((G / r) + (4.1683943e-8 / r)) * ((m2 * m1) / r)   
	7         0.000163  ((3.0700082e-8 / (r * (-2.0268338 + r))) + (G ...   
	8         0.000751  ((m2 * m1) / r) * (G / (((0.99999994 - (-6.996...   
	9         0.009246  (G / (((0.99999994 - ((r * -9.871207e-9) * (r ...   
	
	           loss  complexity  
	0  1.410131e-02           1  
	1  1.038359e-02           3  
	2  6.306039e-03           5  
	3  3.268024e-03           7  
	4  5.465073e-16           9  
	5  5.438011e-16          11  
	6  5.321438e-16          13  
	7  5.317968e-16          17  
	8  5.302009e-16          21  
	9  5.204865e-16          23  
]

  - outputs/20250927_215048_W22Tys/hall_of_fame.csv


In [63]:
model.sympy()

G*m1*m2/(r*r)

In [64]:
# Define the symbolic variable
x0 = sympy.symbols('x0')

# Build each part of the expression
expr = (sympy.simplify(model.sympy()))

# Optionally simplify or expand the expression
expanded_expr = sympy.expand(expr)
expanded_expr

G*m1*m2/r**2

In [27]:
# "sq_dif(x, x_0) = abs(x-x_0)^2"
# extra_sympy_mappings={"sq_dif": lambda x,x0: (abs(x - x0))**2}
#extra_sympy_mappings={"sq_dif": lambda x,x0: 1/((abs(x - x0))**2), 
    #                      "num" : lambda x,x0: x*x0 },

In [ ]:
# Learn equations
model = PySRRegressor(
    niterations=600,
    #niterations=1000,
    binary_operators=["+", "-", "/", "biprod(x,y) = x*y"],
    unary_operators=["sqr(x) = x^2"],
    extra_sympy_mappings={"sqr": lambda x: x**2, "biprod": lambda x,y: x*y},
    maxsize = 50
)

model.fit(X, y, variable_names=["m1", "m2", "G", "x1", "x2", "y1", "y2", "z1", "z2"])

/home/paolo/.conda/envs/coderefinery/lib/python3.11/site-packages/pysr/sr.py:1469: UserWarning: Note: Using a large maxsize for the equation search will be exponentially slower and use significant memory.
  warnings.warn(
/home/paolo/.conda/envs/coderefinery/lib/python3.11/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(


In [ ]:
model.sympy()

In [ ]:
# Define the symbolic variable
x0 = sympy.symbols('x0')

# Build each part of the expression
expr = (sympy.simplify(model.sympy()))

# Optionally simplify or expand the expression
expanded_expr = sympy.expand(expr)
expanded_expr